### ISSUE TITLE
Cannot sign in with Twitter - 500 Internal Server Error 

### ISSUE THREAD

**Issue by ptmt** [themylogin/thelogin.ru#1]
Getting this after redirect from Twitter `http://thelogin.ru/authorization/twitter/callback/?from=http%3A%2F%2Fthelogin.ru%2F&oauth_token=msot94MV10kum5722PtMbCcmZScWuIVu&oauth_verifier=msot94MV10kum5722PtMbCcmZScWuIVu`

![image](https://cloud.githubusercontent.com/assets/1004115/5691943/aaee52d0-9900-11e4-88b9-62d4a2f8768a.png)

**Comment by themylogin** [comment]
Please try it again, there was no exception tracker at the moment (now there is with 7563c28c19df6deff7722ed4e0f08c975837a69b)

**Comment by ptmt** [comment]
ok, just reproduced the error again

**Comment by ptmt** [comment]
:+1:
